### ISSUE TITLE
Unknown device type for Nvidia 4090 rtx

### ISSUE THREAD

**Issue by Sixzero** [pc2/GPUInspector.jl#11]
Code
```
using GPUInspector
gpus()
gpuinfo()
```
Error
```
1 device:
  0: NVIDIA GeForce RTX 4090 (sm_89, 22.434 GiB / 23.988 GiB available)
ERROR: Unknown device type
Stacktrace:
 [1] error(s::String) @ Base ./error.jl:35
 [2] ncudacores @ ~/.julia/packages/GPUInspector/pvxdm/src/gpuinfo.jl:266 [inlined]
 [3] ncudacores(device::CuDevice) @ GPUInspector ~/.julia/packages/GPUInspector/pvxdm/src/gpuinfo.jl:230
 [4] gpuinfo(dev::CuDevice; io::Base.TTY) @ GPUInspector ~/.julia/packages/GPUInspector/pvxdm/src/gpuinfo.jl:15
 [5] gpuinfo(dev::CuDevice) (repeats 2 times) @ GPUInspector ~/.julia/packages/GPUInspector/pvxdm/src/gpuinfo.jl:12
 ...
```
Checked the code, and I think it would be informative it it would show the "minor" variable value in the error, so we could fix it fast.

**Comment by Sixzero** [comment]
Okay, just to not for the fix:
`@show minor, mp, cores`
gives: 
`(minor, mp) = (0x00000009, 128)`
I guess the minor code will be 9 in this case.

**Comment by carstenbauer** [comment]
Quick research: Ada Lovelace architecture seems to have 128 CUDA cores per SM. In your case (NVIDIA 4090 RTX) this means `128 * 128 = 16384` CUDA cores. I would therefore think that `cores = mp * 128` is the correct modification of `ncudacores` for this architecture.

**Comment by carstenbauer** [comment]
> I guess the minor code will be 9 in this case.

Yes. You can also already see that from the output

```
1 device:
  0: NVIDIA GeForce RTX 4090 (sm_89, 22.434 GiB / 23.988 GiB available)
[...]
```

Here, the `sm_89` means major version 8 and minor version 9.

**Comment by carstenbauer** [comment]
Would be great if you could try `GPUInspector#main` and check that things are working.

**Comment by Sixzero** [comment]
Aw, nice that you did merge it, while I was away!
